### ISSUE TITLE
Multiple transactions in one test

### ISSUE THREAD

**Issue by nward** [igortg/pytest-async-sqlalchemy#3]
Hi! Firstly thanks for this project, it's very useful.

I'd like to write a test which executes two transactions - my current use case is an updated_at column which has `onupdate=func.now()`. func.now() gets the transaction time, rather than wall clock time. That's what I want during normal application usage - however in testing I cannot check that it's being changed.

Is there a way to achieve this with this package as is?

**Comment by igortg** [comment]
Sorry that I took so long to answer.

Have you tried to call `db_session.commit()` within the test and then check that `updated_at` column has changed?
