### ISSUE TITLE
Alembic compatibility

### ISSUE THREAD

**Issue by saichenko** [igortg/pytest-async-sqlalchemy#5]
As i undersand, this project currently support db initializing only with `Base.metadata.create_all`. I think, it will be a good feature of setting up tables using Alembic migrations.

**Comment by igortg** [comment]
Can you help me design that by detailing your requirements? I thought in defining a fixture where the user can override to customize database initialization.

What do you need to use alembic to initialize the DB? The SQLAlchemy engine or the database URL string would be enough?

**Comment by saichenko** [comment]
[Example](https://gist.github.com/saichenko/508e43c2e1169c86d91b0c322ce65d07) of setting up a database using Alembic
